### ISSUE TITLE
Add a Internship Selection To Profile Page

### ISSUE THREAD

**Issue by kmcrayton7** [JrDevMentoring/jr_dev_mentoring#28]
Add a internship selection checkbox to the members profile page

**Comment by SundayAdefila** [comment]
I thought we wanted the `internship` option to be open to the general community of users irrespective of their roles? to either post internship positions or apply?

**Comment by kmcrayton7** [comment]
I thought this would be the option for those who only wanted to post an internship. In this case, if there's no checkbox, how would they be directed to the internship part only?

**Comment by SundayAdefila** [comment]
If they are none of the available role options, neither `mentor` nor `mentee`, then it means that by default, we take it as they at least have internship interests and rights.
