### ISSUE TITLE
Change the text on signed out home page

### ISSUE THREAD

**Issue by kmcrayton7** [JrDevMentoring/jr_dev_mentoring#29]
From: "Sign up for free to gain access to our community of mentors and mentees."

To: "Sign up to gain FREE access to our community of mentors, mentees and internships."

**Comment by jmkoni** [comment]
Added a comment on the PR. Oxford commas are important. Should be `mentors, mentees, and internships`.

**Comment by SundayAdefila** [comment]
Deployed!
