### ISSUE TITLE
Add a description to the "I am NOT available"

### ISSUE THREAD

**Issue by kmcrayton7** [JrDevMentoring/jr_dev_mentoring#31]
Add a description to the profiles page that explains that members can make themselves unavailable instead of having to cancel their account 

<img width="362" alt="jrdevmentoring" src="https://cloud.githubusercontent.com/assets/9155255/22793411/c12614ce-eebd-11e6-86f7-f6a7939eb980.png">

**Comment by jmkoni** [comment]
Did this as part of #32 https://github.com/JrDevMentoring/jr_dev_mentoring/pull/46
