### ISSUE TITLE
Refine Edit Profile Form

### ISSUE THREAD

**Issue by erikthedeveloper** [JrDevMentoring/jr_dev_mentoring#32]
Here are a few suggested items for improvement based on my experience signing up.

### Ambiguous Checkboxes/Labels

While creating my own profile, I ran into some minor confusion on the signup / create profile form. I'm not sure which box to check here. I feel like this is ambiguous as-is. Perhaps this could be phrased more clearly such as:

> Are you looking to find a mentor? Be a mentor? Check boxes that apply.

<img width="362" alt="jrdevmentoring" src="https://cloud.githubusercontent.com/assets/1240178/22793454/1ec25da6-eead-11e6-8d72-9e6bf8eff778.png">

Also, the checkboxes could be better spaced out, perhaps a few Bootstrap classes/wrappers could be applied. See example here http://getbootstrap.com/css/#default-stacked

![image](https://cloud.githubusercontent.com/assets/1240178/22793748/fc8cd42c-eead-11e6-8105-12754d36e601.png)

### Clarify "Not available"

I'm assuming that checking this box leaves your profile intact, but somehow flags you as "not available". Maybe this could benefit from a small textual description such as:

> Leave my profile intact, but indicate to mentors/mentees that I am currently unavailable.

![image](https://cloud.githubusercontent.com/assets/1240178/22793555/70334bc8-eead-11e6-989a-a4d6f70a25c5.png)

**Comment by jmkoni** [comment]
I can probably knock this out tomorrow.

**Comment by SundayAdefila** [comment]
Deployed!
