### ISSUE TITLE
Add ability to search/filter the community list by tech stack

### ISSUE THREAD

**Issue by SundayAdefila** [JrDevMentoring/jr_dev_mentoring#42]
Right now, the community page is a long list of devs... It would be cool to be able to easily filter these by tech stack of interest

So as an example, if I'm on the community page, and I need to get a mentor/mentee who has Python as one of his tech stacks, I should be able to type in python to a search/filter field, and have the page only show me devs relating to Python.

**Comment by jmkoni** [comment]
Gonna look into this.

**Comment by jmkoni** [comment]
https://github.com/JrDevMentoring/jr_dev_mentoring/pull/44

**Comment by jmkoni** [comment]
Will look like this:
<img width="1146" alt="screen shot 2017-05-10 at 10 28 23 am" src="https://cloud.githubusercontent.com/assets/1082370/25908767/0b4d39ea-3579-11e7-8784-5c76aa54d5ae.png">

**Comment by SundayAdefila** [comment]
Deployed and confirmed...

Closing issue.
